services:
  mysql:
    image: mysql:latest
    network_mode: ${DOCKER_NETWORK_MODE}
    restart: always
    environment:
      MYSQL_DATABASE: ${APP_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${APP_DB_PASSWORD}
      MYSQL_TCP_PORT: ${EXTERNAL_APP_DB_PORT}

  minio:
    image: minio/minio
    network_mode: ${DOCKER_NETWORK_MODE}
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
      MINIO_EXTERNAL_PORT: ${MINIO_EXTERNAL_PORT}
      MINIO_INTERNAL_PORT: ${MINIO_INTERNAL_PORT}
      MINIO_EXTERNAL_PORT_HTTPS: ${MINIO_EXTERNAL_PORT_HTTPS}
      MINIO_INTERNAL_PORT_HTTPS: ${MINIO_INTERNAL_PORT_HTTPS}
    command: server /data --console-address ":${MINIO_EXTERNAL_PORT_HTTPS}" --address ":${MINIO_EXTERNAL_PORT}"
    volumes:
      - minio_data:/dat

  spring-boot-app:
    image: volunnearapp:latest
    network_mode: ${DOCKER_NETWORK_MODE}
    restart: on-failure
#    ports:
#      - "5005:5005"  # Порт для удаленного дебага
#      - "9999:9999"  # Порт для JMX
#      - "9998:9998"  # Порт для RMI
    depends_on:
      - mysql
      - minio
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - EXTERNAL_APP_PORT=${EXTERNAL_APP_PORT}
      - APP_JWT_TOKEN_SECRET=${APP_JWT_TOKEN_SECRET}
      - APP_JWT_TOKEN_LIFETIME=${APP_JWT_TOKEN_LIFETIME}
      - APP_DB_URL=${APP_DB_URL}
      - APP_DB_USERNAME=${APP_DB_USERNAME}
      - APP_DB_PASSWORD=${APP_DB_PASSWORD}
      - APP_DB_DRIVER_CLASS_NAME=${APP_DB_DRIVER_CLASS_NAME}
      - APP_MAIL_HOST=${APP_MAIL_HOST}
      - APP_MAIL_PORT=${APP_MAIL_PORT}
      - APP_EMAIL_USERNAME=${APP_EMAIL_USERNAME}
      - APP_EMAIL_PASSWORD=${APP_EMAIL_PASSWORD}
      - FRONTEND_HOST=${FRONTEND_HOST}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - MINIO_API_URL=${MINIO_API_URL}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_UPLOAD_URL=${MINIO_UPLOAD_URL}

volumes:
  minio_data:
