services:
  mysql:
    image: mysql:latest
    network_mode: ${DOCKER_NETWORK_MODE}
    restart: always
    environment:
      MYSQL_DATABASE: ${APP_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${APP_DB_PASSWORD}
      MYSQL_TCP_PORT: ${EXTERNAL_APP_DB_PORT}

  spring-boot-app:
    image: volunnearapp:latest
    network_mode: ${DOCKER_NETWORK_MODE}
    restart: on-failure
    depends_on:
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - EXTERNAL_APP_PORT=${EXTERNAL_APP_PORT}
      - APP_JWT_TOKEN_SECRET=${APP_JWT_TOKEN_SECRET}
      - APP_JWT_TOKEN_LIFETIME=${APP_JWT_TOKEN_LIFETIME}
      - APP_DB_URL=${APP_DB_URL}
      - APP_DB_USERNAME=${APP_DB_USERNAME}
      - APP_DB_PASSWORD=${APP_DB_PASSWORD}
      - APP_DB_DRIVER_CLASS_NAME=${APP_DB_DRIVER_CLASS_NAME}
      - APP_MAIL_HOST=${APP_MAIL_HOST}
      - APP_MAIL_PORT=${APP_MAIL_PORT}
      - SENDER_EMAIL_USERNAME=${SENDER_EMAIL_USERNAME}
      - SENDER_EMAIL_PASSWORD=${SENDER_EMAIL_PASSWORD}
      - FRONTEND_HOST=${FRONTEND_HOST}
      - FRONTEND_PORT=${FRONTEND_PORT}

