services:
  mysql:
    image: mysql:latest
    ports:
      - "${EXTERNAL_APP_DB_PORT}:${INTERNAl_APP_DB_PORT}"
    restart: always
    environment:
      MYSQL_DATABASE: ${APP_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${APP_DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql


  minio:
    image: minio/minio
    ports:
      - "${MINIO_EXTERNAL_PORT}:${MINIO_INTERNAL_PORT}"
      - "${MINIO_EXTERNAL_PORT_HTTPS}:${MINIO_INTERNAL_PORT_HTTPS}"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":${MINIO_EXTERNAL_PORT_HTTPS}"
    volumes:
      - minio_data:/data

  spring-boot-app:
    image: volunnearapp:latest
    ports:
      - "${EXTERNAL_APP_PORT}:${EXTERNAL_APP_PORT}"
    build:
      context: .
    restart: on-failure
    depends_on:
      - mysql
      - minio
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - EXTERNAL_APP_PORT=${EXTERNAL_APP_PORT}
      - APP_JWT_TOKEN_SECRET=${APP_JWT_TOKEN_SECRET}
      - APP_JWT_TOKEN_LIFETIME=${APP_JWT_TOKEN_LIFETIME}
      - APP_DB_URL=${APP_DB_URL}
      - APP_DB_USERNAME=${APP_DB_USERNAME}
      - APP_DB_PASSWORD=${APP_DB_PASSWORD}
      - APP_DB_DRIVER_CLASS_NAME=${APP_DB_DRIVER_CLASS_NAME}
      - APP_MAIL_HOST=${APP_MAIL_HOST}
      - APP_MAIL_PORT=${APP_MAIL_PORT}
      - SENDER_EMAIL_USERNAME=${SENDER_EMAIL_USERNAME}
      - SENDER_EMAIL_PASSWORD=${SENDER_EMAIL_PASSWORD}
      - FRONTEND_HOST=${FRONTEND_HOST}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - MINIO_API_URL=${MINIO_API_URL}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_UPLOAD_URL=${MINIO_UPLOAD_URL}



networks:
  default:
    driver: bridge

volumes:
  mysql_data:
  minio_data: