DB_URL=jdbc:mysql://localhost:3306/volun_near_app_db?createDatabaseIfNotExist=true
DB_URL=jdbc:mysql://mysql:3306/volun_near_app_db?createDatabaseIfNotExist=true #For docker
DB_USERNAME=root
DB_PASSWORD=12345password