spring:
  datasource:
    url: ${APP_DB_URL}
    username: ${APP_DB_USERNAME}
    password: ${APP_DB_PASSWORD}
    driver-class-name: ${APP_DB_DRIVER_CLASS_NAME}
  jpa:
    open-in-view: false
    generate-ddl: true
  mail:
    host: ${APP_MAIL_HOST}
    port: ${APP_MAIL_PORT}
    username: ${SENDER_EMAIL_USERNAME}
    password: ${SENDER_EMAIL_PASSWORD}
    properties.mail.smtp:
      auth: true
      starttls-enable: true
    protocol: smtp
  sql:
    init:
      data-locations: classpath:roles.sql
      mode: always
server:
  forward-headers-strategy: framework
  port: ${EXTERNAL_APP_PORT}
  error:
    include-exception: true
    include-message: always
    include-binding-errors: always
jwt:
  token:
    secret: ${APP_JWT_TOKEN_SECRET}
    lifetime: ${APP_JWT_TOKEN_LIFETIME}

management:
  endpoints:
    web:
      exposure:
        include: env,health,info
  endpoint:
    env:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.boot.actuate.env.EnvironmentEndpoint: DEBUG
