package com.volunnear.dtos.enums;

public enum ActivityType {
    UNKNOWN, FAMILY, SPORT, EDUCATION, ENVIRONMENT, HEALTH, COMMUNITY, CULTURE, TECHNOLOGY, ANIMAL_CARE, ELDERLY_CARE,
    DISASTER_RELIEF, ARTS, MUSIC, CHILDREN, OTHER;
}
